---
all:
  children:
    control_plane:
      hosts:
        master-0.example.com:
          ansible_host: 10.0.0.10
          openshift_node_name: master-0.example.com
          openshift_etcd_restore_node: true
        master-1.example.com:
          ansible_host: 10.0.0.11
          openshift_node_name: master-1.example.com
          openshift_etcd_restore_node: false
        master-2.example.com:
          ansible_host: 10.0.0.12
          openshift_node_name: master-2.example.com
          openshift_etcd_restore_node: false
