---
galaxy_info:
  role_name: execute_restore
  namespace: openshift_etcd_restore
  author: Tristan Scholten
  description: Execute host-side OpenShift etcd restore up to CSR approval.
  license: MIT
  min_ansible_version: "2.15"

dependencies: []
