---
galaxy_info:
  role_name: approve_csrs
  namespace: openshift_etcd_restore
  author: Tristan Scholten
  description: Approve or explain OpenShift pending CSR approval after etcd restore.
  license: MIT
  min_ansible_version: "2.15"

dependencies: []
