---
- name: Preflight OpenShift etcd restore prerequisites
  hosts: all
  gather_facts: false
  roles:
    - role: restore_node_selection
      tags:
        - restore_node_selection
        - preflight
    - preflight
