---
- name: Prepare Kasten etcd restore target namespace and volume
  hosts: localhost
  gather_facts: false
  roles:
    - role: restore_node_selection
      tags:
        - restore_node_selection
        - prepare
    - kasten_restore_target
