---
- name: Wait for Kasten to place etcd snapshot on restore node
  hosts: control_plane
  gather_facts: false
  roles:
    - role: restore_node_selection
      tags:
        - restore_node_selection
        - wait_for_snapshot
    - wait_for_snapshot
